name: deploy-dev

on:
  push:
    branches: ["develop"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Hub Login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Dev Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sopkathon-server-ios2:dev-blue .
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sopkathon-server-ios2:dev-green .

      - name: Push Dev Images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sopkathon-server-ios2:dev-blue
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sopkathon-server-ios2:dev-green

      - name: Deploy to Dev EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.DEV_EC2_SSH_KEY }}
          script: |
            bash /home/ubuntu/deploy.sh dev
