name: deploy-prod

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Hub Login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Prod Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sopkathon-server-ios2:prod-blue .
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sopkathon-server-ios2:prod-green .

      - name: Push Prod Images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sopkathon-server-ios2:prod-blue
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sopkathon-server-ios2:prod-green

      - name: Deploy to Prod EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.PROD_EC2_SSH_KEY }}
          script_stop: true
          command_timeout: 20m
          script: |
            bash -lc "bash /home/ubuntu/deploy.sh prod"
      
